version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/mimic
        ports:
            - '8000:8000'
        depends_on: 
            - db
        tty: true
        command: /bin/sh -c "while sleep 1000; do :; done"
    db:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - db_volume:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes:
    db_volume: