
version: '3.9'

services:
    nginx:
        build: ./nginx
        ports:
            - '8000:80'
        volumes:
            - static_volume:/mimic/static
            - media_volume:/mimic/media
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                - SECRET_KEY=${SECRET_KEY}
                - POSTGRES_DB=${POSTGRES_DB}
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        expose: 
            - 8000
        volumes: 
            - static_volume:/mimic/static
            - media_volume:/mimic/media
        command: ../docker-entrypoint.sh
        depends_on:
            - db
        tty: true
    db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
    db_volume:
    static_volume:
    media_volume: